/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.robertsgrants.ringalgorithm;

import java.awt.Graphics;
import java.awt.MouseInfo;
import java.awt.event.InputEvent;
import java.awt.geom.Point2D;

/**
 *
 * @author Hallow
 */
public class Circle extends javax.swing.JPanel {

    /**
     * Creates new form Circle
     */
    public Circle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        jButton1.setText("Draw");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("R=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton1ActionPerformed

    int Xc, Yc;
    int Rx, Ry;
    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        if ((evt.getModifiers() & InputEvent.BUTTON1_MASK) != 0) {

            System.out.println("Left mouse button clicked with cords " + evt.getX() + " " + evt.getY());
            Xc = evt.getX();
            Yc = evt.getY();
        }
        if ((evt.getModifiers() & InputEvent.BUTTON3_MASK) != 0) {
            System.out.println("Right mouse button clicked with cords " + evt.getX() + " " + evt.getY());
            Rx = evt.getX();
            Ry = evt.getY();
            Circle();
        }


    }//GEN-LAST:event_jPanel1MouseClicked

    private void Circle() {

        Graphics g = jPanel1.getGraphics();
        g.drawLine(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        g.drawLine(0, jPanel1.getHeight(), jPanel1.getWidth(), 0);
        g.drawLine(0, jPanel1.getHeight() / 2, jPanel1.getWidth(), jPanel1.getHeight() / 2);
        g.drawLine(jPanel1.getWidth() / 2, 0, jPanel1.getWidth() / 2, jPanel1.getHeight());

        int R = (int) Point2D.distance(Xc, Yc, Rx, Ry);
        int pn = 1 - R;
        int xn = 0;
        int yn = R;
//        int Xc = jPanel1.getWidth() / 2; // X ass centram
//        int Yc = jPanel1.getHeight() / 2; // Y ass centram

        while (xn <= yn) {
            if (pn < 0) {
                xn++;
                pn = pn + 2 * xn + 1;
            } else {
                xn++;
                yn--;
                pn = pn + 2 * xn + 1 - 2 * yn;
            }
            // Vertical

            g.fillRect(xn + Xc, yn + Yc, 1, 1);
            g.fillRect(-xn + Xc, yn + Yc, 1, 1);
            g.fillRect(xn + Xc, -yn + Yc, 1, 1);
            g.fillRect(-xn + Xc, -yn + Yc, 1, 1);

            // Horizontal
            g.fillRect(Xc + yn, Yc + xn, 1, 1);
            g.fillRect(Xc - yn, Yc + xn, 1, 1);
            g.fillRect(Xc + yn, Yc - xn, 1, 1);
            g.fillRect(Xc - yn, Yc - xn, 1, 1);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
